### ISSUE TITLE
 Unclear error message when context other than default is used with Single, Compose, and Compose Debugging

### ISSUE THREAD

**Issue by BigMorty** [docker/compose-cli#1096]
**For example, If I am using an ACI context and use the following commaind:**
> docker build --rm --pull -f "C:\Users\...\python-sample-vscode-django-tutorial/Dockerfile" --label "com.microsoft.created-by=visual-studio-code" -t "pythonsamplevscodedjangotutorial:latest" "C:\Users\...\python-sample-vscode-django-tutorial" <

**I get the following output which is not very usefull:**
unknown command "build" for "docker"
The terminal process terminated with exit code: 1.

A better error message is definitely needed, maybe even an easy way to switch back to the default context (although maybe that is something our VS Code Docker extension would be better suited to do, lets talk).

**Comment by gtardif** [comment]
Thx @BigMorty for reporting this, actually it has been fixed already, but not yet shipped in Desktop. 
FYI, we used to display an explicit message to the user saying they need to switch back to the default context (for known commands in default). This bug is a regression, side effect of shipping the docker cli v20.10.

**Comment by gtardif** [comment]
```
$ docker build -t centosdebug ./centos/
Command "build" not available in current context (acicontext), you can use the "default" context to run this command
```

**Comment by BigMorty** [comment]
Great to hear, thanks @gtardif
