### ISSUE TITLE
Prompt users to use docker compose from docker-compose

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1149]
In `docker-compose` general help and for the `up` command, prompt users to use `docker compose`. Only do this for Windows and macOS.

`up` message: "Docker Compose is now in the Docker CLI, try `docker compose up`"

Add at the top of the `up` output with a new line after it so that it's more visible.

```console
docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "tmp_default" with the default driver
Pulling front (nginx:)...
latest: Pulling from library/nginx
```

`help` message: "Docker Compose is now in the Docker CLI, try `docker compose`"

Add at the bottom of the help message.

```console
...
  unpause            Unpause services
  up                 Create and start containers
  version            Show version information and quit

Docker Compose is now in the Docker CLI, try `docker compose`
```

**Comment by gtardif** [comment]
Add this only for mac/windows users for now, as compose-cli might not be available for linux users

**Comment by gtardif** [comment]
Do this only in docker-compose help ? @mkvitnitsky

**Comment by henrik242** [comment]
Also, is this suspected to be the default behaviour in Linux any time soon?

**Comment by natewiebe13** [comment]
> Also, is this suspected to be the default behaviour in Linux any time soon?

Would also like to know this as we're starting to write tooling around this.

**Comment by driesvints** [comment]
@natewiebe13 that's indeed super confusing. I was also under the impression that this was stable based on the message from that's given from `docker-compose`.

**Comment by danilopolani** [comment]
Side note: looking at the [releases notes of the latest version](https://docs.docker.com/compose/release-notes/#1292), it says:

> Removed the prompt to use docker compose in the up command.

Maybe they're not pushing users to switch to that syntax?

**Comment by Chealer** [comment]
> **Edit:** Was able to answer this for myself by reading https://docs.docker.com/compose/cli-command/, though it does seem strange to recommend using something that's in preview without mentioning that it's a preview/shouldn't be used in production. Without reading the link, one might assume it's good to start replacing instances of `docker-compose`.

I'm afraid @natewiebe13 is quite right. I upgraded to Docker Desktop for Windows 3.3.3 and started seeing that message. I then switched to docker compose up, and later realized my application was unusable due to broken networking. I thought the upgrade was the cause, so it took me 10 minutes to figure out I simply needed to go back to docker-compose.

**Comment by thaJeztah** [comment]
@Chealer if you have steps to reproduce your problem, could you open a ticket with steps to reproduce the networking problem you ran into?

**Comment by Chealer** [comment]
@thaJeztah reproducing my case would be as easy as switching a dash to a space for me. The problem is one container can't ping the other by hostname, surely because DNS doesn't resolve. The hostname is defined as an alias.

That being said, thanks for asking, and to actually answer your question: I could, but I don't know Docker networking nearly enough to positively affirm that `docker compose up`'s behavior is incorrect. We came up with a docker-compose.yml which works after quite some work, but I have no idea if the specification mandates that it works, or if we are relying on undocumented behavior.

However, if I was to see an authoritative source clearly (explicitly) indicate that `docker compose up` and `docker-compose up` are currently supposed to be functionally equivalent, then I would report my case.

**Comment by JackOfSpade** [comment]
Yeah... I'm not touching this until next year or we get a stable version.
