### ISSUE TITLE
docker compose run displays orphans warning, detecting other containers as orphans

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1199]
When running `docker compose run`, we filter the compose project and keep only the selected service to run and dependencies. Reusing the code to start the requested services, this detect all other services as orphans and displays a warning. 
We need to not display this warning when filtering services. 

The same bug most likely also happens when running `docker compose up SERVICE1, SERVICE2`

**Comment by ndeloof** [comment]
we need to pass the whole project to backend, so `filter` must mark excluded services but not remove them. I suggest we move the `filter` logic to compose-go `Project` and introduce a `Disabled` flag, which will be usefull otherwise to implement profiles (https://github.com/compose-spec/compose-go/issues/80)
