### ISSUE TITLE
Best practices question re: connecting to AWS RDS

### ISSUE THREAD

**Issue by al-dpopowich** [docker/compose-cli#1382]
I have compose file that's working well with a container based on a stock `postgresql:12.4-alpine` image.  This is perfect for development and testing, however, for production we want to use a managed database, specifically a RDS instance (an aurora-postgresql cluster).

My question is regarding best practices for allowing communication between my generated ECS stack and the preexisting RDS cluster.

I do not want my RDS available publicly so I need to create my stack in the same Security Group (SG), or otherwise manually configure network security to allow inbound traffic.

That is, one of:
* make my stack's default network the same as my RDS' SG, e.g., at the root of my compose file:
  ```yaml
  networks:
     default:
        external: true
        # aurora cluster SG
        name: sg-123abc
  ```  
* allow an INBOUND rule into the RDS' Security Group (SG) from the generated stack's SG.
  
Either way, I have a situation where I lose the "magic" of `docker compose up` and have to do manual edits, in a bit of a chicken-and-egg situation.  Also maintaining/purging resources becomes a potential maintenance headache since they're not included in the cloudformation stack.

Am I missing something simple or do I have to jump through these hoops?

Regardless, here's a big thumbs up for #726.

**Comment by robogeek** [comment]
I have a Github repository with some examples of one method to do this.  The repository is a companion to my book _Deploying Docker Containers to AWS using Terraform_

The idea I developed is to

* Use Terraform to deploy an RDS instance, and anything else you need, such as a load balancer, or domain name settings
* Export from Terraform scripts a shell script to run the `docker compose` command
* Environment variables are used to pass config data -- such as the database particulars for the RDS instance -- as either environment variables or a Docker Secret
* In the Compose file, reference the environment variables or Secrets

Code is here:  https://github.com/robogeek/terraform-docker-aws-examples/tree/docker-ecs

**Comment by ndeloof** [comment]
Support for `external` networks have been suggested for such use-cases. Obviously your RDS SecurityGroup need to be configured to support INBOUND from services. Would need to investigate if we can create some additional CloudFormation resources to create such a rule
Otherwise, I wonder you can configure such a INBOUND rule based on service tags? If feasible, then you can create your RDS database and SecurityGroup so it allows traffic from services, before you run `compose up`, as long as you allow access to `com.docker.compose.service` tagged services.

**Comment by riwiki** [comment]
Not sure about the tag-idea, but what you can do is to allow inbound traffic from any resource bound to a certain security group. E.g. your database-sg (security-group) allows inbound 3306 traffic from the database-user-sg; both groups are provisioned externally, e.g. terraform. If I was just able to attach database-user-sg to my ECS task via the compose file, the use case is solved.

**Comment by robogeek** [comment]
@riwiki Please take a look at the workspace I linked above.  It shows one method to do what you said.  This is spelled out in my book, but the idea I developed was -- In Terraform, to generate a shell script (using a `templatefile` function) that sets environment variables from Terraform values.  Then, rather than running `docker compose up` you run the shell script and that sets environment variables, and inside the Compose file you reference the environment variable.

That worked fine for simple values.  When it came to generating a complex Cloud Formation Overlay, I instead found it necessary to use the `yamlencode` function to take a Terraform datastructure representing the Overlay, convert that into a YAML text snippet, and then use a `templatefile` function to directly generate the Compose file.

Because Compose files are YAML it seems possible to completely generate the Compose file from Terraform code.  But I didn't take it that far.

For your example you'd do:

```
networks:
   default:
      external: true
      # the RDS database sg allows INBOUND traffic to database-user-sg, provisioned outside of Composer
      name: ${RDS_SECURITY_GROUP}
```

Then you somehow set that environment variable appropriately before running `docker compose up`.

The code is in the Github repository, there is a writeup in the book.  I hope my summary helps.

**Comment by al-dpopowich** [comment]
Thanks all for you suggestions.  In the end this is what I did:

1. Create a python script that reads a configuration file which will indicate whether a deployment is going to use the test pg container or use rds.  The script also reads in the compose file (using pyyaml) as a python dict.
2. If using RDS, the script ensures the cluster exists (the name of which is based on the stack name, i.e., the name is deterministic, so I know if it exists or not).  If it doesn't exist, the script will prompt the user to run again with options that state explicitly to create AWS resources if they don't exist.  Based on info in the config file, the RDS cluster is created (using boto3). And here's the important part: *if creating a cluster, the script first creates a SecurityGroup and places the cluster in that SG.*  Regardless of being found or created, the SG of the rds cluster is noted.
3. The script then injects/removes services from the compose dict as necessary, e.g., remove the "pg" key from the services so the default postgresql container is not created and, having noted a SG was created for RDS, add a default network:
```yaml
networks:
   default:
      external: true
      # aurora cluster SG
      name: sg-123abc
```
4. The script sets the COMPOSE_FILE environment variable to "-" (stdin) and runs a subprocess, `docker compose ...` writing the compose dict (converted back to yaml)  to stdout:
```python
      os.environ['COMPOSE_FILE'] = '-' # stdin
      proc = subprocess.run(['docker', 'compose'] + command,
                                          input=yaml.dump(compose_file),
                                          text=True)
```

**Comment by tkrotoff** [comment]
This issue should be re-opened
