### ISSUE TITLE
Deploy Image to Azure Container Instance... results in AADSTS70011 error

### ISSUE THREAD

**Issue by MPerkins-msft** [docker/compose-cli#1482]
**Description**
Using VS code to deploy my image to Azure container instance it loads up my internet browse and asks if i want to switch profiles so i answer No, thanks as my Azure subscription is linked to my home account. After clicking no i see Sorry, but we're having trouble signing you in AADSTS70011.

**Steps to reproduce the issue:**
1. Load docker desktop
2. Load VS code loading the Rust folder from which the image was created
3. Go to the docker tab and select registries panel
4. Open up the Azure->subscription->resource group->container registry->Tag (latest1)
5. Right click on tag and select Deploy Image to Azure Container Instance...
6. Create new ACI context... name it azurecontext
7. Select the container registry that already exists in Azure
8. Edge opens up and displays the switch profiles dialog pops up and select no thanks
9. Error form displayed

**Describe the results you received:**
First URL loaded
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?response_type=code&client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&redirect_uri=http://localhost:57712&state=4i7qr3hflt&prompt=select_account&response_mode=query&scope=offline_access

Second URL
https://management.azure.com/.default
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

**Describe the results you expected:**
My docker instance is loaded into Azure

**Additional information you deem important (e.g. issue happens only occasionally):**
Right clicking on the Azure container registry and selecting Open in portal works great.

Request Id: 060d1286-36c9-4355-b9c8-3e82411de200
Correlation Id: be7e87c9-2421-431a-a9e2-896b4877b15c
Timestamp: 2021-03-30T23:17:00Z
Message: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope offline_access is not valid. offline_access scope request must include either openid scope or a resource scope.
**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: AMI2:LLOY:Q4PG:VA3D:4H54:MQDA:73AO:R3Y6:QU4E:COHQ:Z5IE:VFYV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Microsoft Azure CLI 2.19.1
VS code
   Version: 1.54.3 (user setup)
   Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
   Date: 2021-03-15T10:55:45.459Z
   Electron: 11.3.0
   Chrome: 87.0.4280.141
   Node.js: 12.18.3
   V8: 8.7.220.31-electron.0
   OS: Windows_NT x64 10.0.19041

**Comment by gtardif** [comment]
From the description, I think this might be dues to authentication in the Docker ACI integration that is isolated from browser  authentication and `az` command line . 
@karolz-ms I assume the VSCode Docker extension does invoke `docker login azure` if needed, and even if already logged in in Azure portal, you need to confirm the login so that the Docker cli gets actually logged in to azure and can perform further operations. Do you have any idea to make this scenario easier to understand / more fluid in the Docker VSCode extension ?

**Comment by karolz-ms** [comment]
@gtardif the issue here is that the `scope` parameter in the URL is not quoted properly. The value of the parameter is `offline_access https://management.azure.com/default` and it should be quoted as `offline_access+https%3a%2f%2fmanagement.azure.com%2f.default`

I am not sure why this is happening--I could not reproduce the problem on my machine--but I think it is the Docker CLI, or maybe Azure Go SDK used by the Docker CLI, that is responsible for constructing the URL as part of authN sequence, that is why I advised @MPerkins-msft to open a bug here.

To answer your question, yes, we do `docker login azure` always because there is no way for us at the moment to ask Docker CLI "do you have an Azure token and is it still valid?". As far as I remember, if the user does have a valid token, the command just succeeds with no user interaction, so we deemed that sufficient.
