### ISSUE TITLE
Configuration option to use EC2 instead of Fargate in ECS

### ISSUE THREAD

**Issue by johan123312321** [docker/compose-cli#1484]
**Description**

Currently Fargate containers are used by default in ECS service.
EC2 containers are supported but are used automatically only if GPU resources are requested.

There is no configuration option to manually force deployment to EC2 instead of Fargate.

**Feature Request**
Please add configuration option which type of container (LaunchType) should be used for service (EC2 / FARGATE).

**Justification**
In some architecture cases EC2 containers are preferred over Fargate from pricing perspective.

P.S. As I see from code there is function which decides which type of container should be created and it checks only gpu config.

`func requireEC2(s types.ServiceConfig) bool {
	return gpuRequirements(s) > 0
}`

**Comment by ndeloof** [comment]
EC2 support was introduced only to workaround lack of GPU support on Fargate, with the plan it would be removed once Fargate offer this option. From a technical perspective, EC2 support brings significant extra complexity that I'd prefer to avoid. I didn't know about pricing impacts, need to get a Product decision on this topic

**Comment by davide-malagoli** [comment]
Hi,

we use EC2 launch types, 
because from a princing perspective they are more convenient
when the workload does not scale often.
In our use case the services for most of the time run in a fixed number of replicas,
and only on fixed spike periods need to be scaled up.

Running the same configuration in FARGATE would be expensive, wihout any benefits. 

Most of the benefit of FARGATE can be replicated using awsvpc and cloudmap, we tested it.
And using the right ec2 instance.
For a microservices scenario, we used a1.medium, that enabled us to run up 10 task defintion (derived from docker-compose) on just 2 GB of RAM.

From our perspective a limited support for EC2 ( some advanced features may be missing ) would be sufficient

**Comment by ndeloof** [comment]
That's rally sad AWS doesn't make Fargate more attractive by pricing policy. I would expect Fargate allows better resource allocation/concentration and as such should offer lower costs vs plain dedicated EC2 instances.

**Comment by antgel** [comment]
Another potential use case:
`ECS Fargate does not support bind mounts from host: incompatible attribute`

Let's say, trying to spin up a Taiga instance with a config like [this](https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.yml).

**Comment by knutster** [comment]
Fargate also only supports 4 CPUs and 30G memory, I have routine batch jobs that eat 36 CPUs and 72G memory.
