### ISSUE TITLE
docker compose does not honor build arg while docker-compose does

### ISSUE THREAD

**Issue by princemaple** [docker/compose-cli#1674]
## Description of the issue

I posted this issue at https://github.com/docker/compose/issues/8329.
Only just found out about this repo today. Feel free to close one of them.
`docker compose build` does not honor build arg like `docker-compose` does

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      args:
        MIX_ENV: dev
     ....
```

## Steps to reproduce the issue

1. docker compose build app
2. docker-compose build app

### Observed result

1. it's not passing arg properly, MIX_ENV gets default `prod`
2. gets `dev` properly

### Expected result
works the same

### Stacktrace / full error message

```
N/A
```

## Additional information

win10
docker for win

**Comment by tdilauro** [comment]
I just ran into this today on MacOS Big Sur v11.3.1.

## Description of the issue

`docker compose build` does not honor compose file `build` `args`, but `docker-compose build` does.
Passing `--build-arg arg=value` works the same for both forms of the command.

## Context information (for bug reports)

**Output of `docker-compose version`**

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker compose version`**

```
Docker Compose version 2.0.0-beta.1
```

**Output of `docker version`**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

```
services:
  minimimal-docker-compose-error:
    build:
      context: ./minimal-docker-compose-error
      dockerfile: ./minimal-docker-compose-error/Dockerfile
      args:
        TEST_ARG: test-arg-value
  ...
```

**Contents of Dockerfile**

```
FROM busybox:latest
ARG TEST_ARG

RUN echo "TEST_ARG has value: ${TEST_ARG}"
```

## Steps to reproduce the issue

    1. docker compose build --no-cache
    2. docker-compose build --no-cache


### Observed result

**Output of `docker compose build --no-cache`**
```
...
 => [2/2] RUN echo "TEST_ARG has value: ${TEST_ARG}" 
...
```

**Output of `docker-compose build --no-cache`**
```
...
 => [2/2] RUN echo "TEST_ARG has value: test-arg-value"
...
```

I see similar behavior if I have specified a default value for `ARG TEST_ARG` in the Dockerfile:
- The output from `docker compose build` contains the default value, rather than the unreplaced `${TEST_ARG}` seen above. 
- The output from `docker-compose build` contains the expected value from the compose file.

### Expected result

They behave the same and they both honor the `build` `args` values.

**Comment by ndeloof** [comment]
this issue should be fixed by https://github.com/docker/compose-cli/pull/1679
