### ISSUE TITLE
Docker Compose v2 Beta incompatible with WebODM

### ISSUE THREAD

**Issue by PLSomebody** [docker/compose-cli#1905]
Enabling Docker Compose v2 in Experimental Features on Mac, destroys compatibility with WebODM without any error message.
Docker Desktop version: 3.5.1 (3.5.1.7), macOS Big Sur 11.4 (20F71)

How to reproduce:
1. Install Docker with default features
2. Check if Docker Compose V2 is enabled
3. install WebODM (manual: https://github.com/OpenDroneMap/WebODM/) - 3 steps in terminal:
a. git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input --depth 1
b. cd WebODM
c. ./webodm.sh start
After few seconds script will exit to prompt.

**Comment by ndeloof** [comment]
Root cause for this is that you rely on `compose start` command, expecting it fails due to missing containers to start.
Compose v2 does not rely on available compose file to run `start` but on actual container state. Reason for this is that this compose file might have been updated, or not be available when the command is ran vs initial setup.

Can you please clarify the use-case to run [`start | up`](https://github.com/OpenDroneMap/WebODM/blob/master/webodm.sh#L268)? `up` command actually will just be equivalent to `start` if containers already exists and are configured according to your compose file, there's no benefit to distinguish `start` command in this scenario afaict.
