### ISSUE TITLE
AWS ESC Compose v2: way to explicitly set ReadOnlyRootFS 

### ISSUE THREAD

**Issue by furai** [docker/compose-cli#2093]
Hello,

I've searched the repo and net multiple times. I've read the code of the compose application to understand how it works. 

When enabling ECS Exec with an Overlay I end up with ReadOnlyRootFS being enabled by default by fargate/cloudformation. This in turn made my application go down cause It couldn't write to /tmp. I'd love to be able to explicitly set that flag to something different.

Right now changing it makes me write an overlay that holds whole huge map for TaskDefinition > [ContainerDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html). It's very fragile code and I'd love to avoid it. (I've seen some partial support for merge2 $patch but it didn't help much.)

Cheers,
Furai

**Comment by furai** [comment]
Sorry for bumping - but can anyone explain which repo is for what? I thought that what I was referring to was for version v2 compose in the docker/compose repo?

**Comment by komatom** [comment]
Hey @furai

I've been dealing with that with Fargate for some time and I found out that in August this year they have made some changes which caused this..

for example, I had issue where when I first start the container it couldn't start up because processes can't write their pid files in /run /tmp etc.. but if I start that same deploy again file system was writable and all settings were the same.. Amazon support haven't told me yet why and how to resolve this, but I found a way to wrokaround that by setting the following in your dockerfile:

VOLUME /tmp
VOLUME /run
VOLUME /root
VOLUME /var

essentially all directories you want your writes to work on, the first time you start the container.. it is very off issue, but it is not related to ReadOnlyRootFS, because when it is set to null, that means that fs should be writable, only when it is set to true it should be read-only.

Hope that helps, and it will be nice if you can also open a ticket on Amazon for this

Regards

**Comment by furai** [comment]
Hey @komatom, 

Thank you for your reply. If that's a bug then it's rather serious one. Do you use ECS exec? It would be still nice to be able to enable ECS Exec which would add needed policies and disable RootOnlyFS. 

I'm not really sure where to report it on AWS side, I haven't been using it extensively, I'm just doing some tests for work.

Cheers,
Furai

**Comment by komatom** [comment]
@furai seems like a bug, but it is very hard for the Amazon support to reproduce it, and then to actually get to fix it.. if you mean ExecuteCommand, I do use it
