### ISSUE TITLE
Need guidance to provide target groups parameters

### ISSUE THREAD

**Issue by bcouetil** [docker/compose-cli#2105]
Thank you for this great tool !

I'm deploying successfully to ECS.

But my deployments are painfully slow, and I want to set some target groups parameters like mentioned here : https://nathanpeck.com/speeding-up-amazon-ecs-container-deployments/

How can I do that ? Thanks !

**Comment by JohnPreston** [comment]
All of what's in that blog post is supported for tuning and implemented in [ECS Compose-X](https://docs.compose-x.io).
In [x-elbv2](https://docs.compose-x.io/syntax/compose_x/elbv2.html) you'd find [TargetGroupAttributes](https://docs.compose-x.io/syntax/compose_x/elbv2.html#targetgroupattributes) that allow to tune all of that. It will also detect whether a setting is valid for your type of load-balancer. For other settings, it will try to auto-change values if they are not correct, for example with an NLB, the intervals, or if you have a listener set to TCP (or HTTP with ALB) and have defined certificate(s), auto update to TLS (HTTPS for ALB).
Equally when defining [Services](https://docs.compose-x.io/syntax/compose_x/elbv2.html#services) (which really are the TargetGroups), if the port defined was not declared in the service definition, it would automatically fail and report that error, instead of allowing to continue with a non-functional deployment.

It is a fairly complex module in code but implementing all these auto-correct and early error is here to try to ensure everything will work on deploy.

Hope this helps,

**Comment by bcouetil** [comment]
Thank you for your detailed response 🙏

I managed to do the changes I wanted, but only some of them, because I had a DB TCP port (among HTTP ports) that prevent me to have a HTTP-only load balancer. This was a mistake, next time I'll use managed database, and more optimisations will be available to me.

I'll post here some more example code when I can 😊
