### ISSUE TITLE
Add support for AWS SSO

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#671]
(related to https://github.com/docker/ecs-plugin/issues/166)

ECS integration should support https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html
(this would also help fix aws-okta issue reported [here](https://github.com/docker/ecs-plugin/pull/199#issuecomment-669649000))

**Comment by ndeloof** [comment]
obsolete

**Comment by bizzelicious** [comment]
Hi! How did you get AWS SSO to work with `docker compose`?

**Comment by ndeloof** [comment]
We introduced ECS context based on `AWS_*` environment variables which should allow integration with third-party authentication mechanism. At least this works well with Okta we use internaly.

**Comment by bizzelicious** [comment]
Thanks, your reply gave me a clue and how to solve it :)
If someone else finds this and have issues with using the ecs context with AWS SSO this is how I solved it.

**Issue:**
You are not able to use a ECS context that uses a Profile created by AWS SSO:
```
$ cat ~/.aws/config
[profile myProfile]
sso_start_url = https://d-123456789.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = 123
sso_role_name = DeveloperRole
region = eu-north-1

$ aws sso login --profile myProfile
$ docker context create ecs myProfile
? Create a Docker context using: An existing AWS profile
? Select AWS Profile myProfile
Successfully created ecs context "myProfile"
$ docker compose up -c myProfile
NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
**Root cause:** 
docker compose ecs context  don't understand the sso entries in an AWS profile(?)

**Solution(s):**
Use a wrapper/exporter, such as [aws2-wrap](https://github.com/linaro-its/aws2-wrap) to export AWS SSO credentials to docker compose ecs context.

**Example solution 1 - Use wrapper profile**

This is, in my opinion, the preferred way to solve this since you can have several context pointing to different accounts/environments. 
 It uses uses a credential_process profile in your .aws/config file. It's this credential_process profile you will use when setting up the docker compose ecs context as the credentials_process looks up the needed credentials and exposes them in a way that docker compose ecs context understands.

For more info, see: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html and https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
```
$ cat ~/.aws/config
[profile account1]
sso_start_url = https://d-123456789.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = 123
sso_role_name = DeveloperRole
region = eu-north-1

[profile account1-wrapped]
credential_process = aws2-wrap --process --profile account1

[profile account2]
sso_start_url = https://d-123456789.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = 456
sso_role_name = DeveloperRole
region = eu-north-1

[profile account2-wrapped]
credential_process = aws2-wrap --process --profile account2

$ aws sso login --profile account1

$ docker context create ecs account1
? Create a Docker context using: An existing AWS profile
? Select AWS Profile account1-wrapped
Successfully created ecs context "account1"

$ docker compose up -c account1

$ aws sso login --profile account2

$ docker context create ecs account2
? Create a Docker context using: An existing AWS profile
? Select AWS Profile account2-wrapped
Successfully created ecs context "account2"

$ docker compose up -c account2
````

**Example solution 2 - Use Env variables **
This example uses only one context, so instead of selecting a specific context you want to deploy to, you use the current exported credentials (https://github.com/linaro-its/aws2-wrap#export-the-credentials).
 To deploy to different environments you instead need to run the "eval" command before deploying.
```
$ cat ~/.aws/config
[profile account1]
sso_start_url = https://d-123456789.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = 123
sso_role_name = DeveloperRole
region = eu-north-1

[profile account2]
sso_start_url = https://d-123456789.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = 456
sso_role_name = DeveloperRole
region = eu-north-1

$ docker context create ecs envVariables
? Create a Docker context using: AWS environment variables
Successfully created ecs context "envVariables"

$ aws sso login --profile account1
$ eval "$(aws2-wrap --profile account1 --export)" #docker compose will now deploy to account1
$ docker compose up -c envVariables #Uses the exported env variables from the previous eval command, in this case pointing to account1

$ aws sso login --profile account2
$ eval "$(aws2-wrap --profile account2 --export)" #docker compose will now deploy to account2
$ docker compose up -c envVariables #Uses the exported env variables from the previous eval command, in this case pointing to account2
```

**Comment by pcolmer** [comment]
Just one word of warning about AWS profiles and `docker compose` ... the latter mangles the profile names into lower-case regardless of how they are stored in the AWS config file and `docker compose` then still fails. The only workaround I've found is to ensure that at least the names for the "wrapped" profiles are in lower case.
