### ISSUE TITLE
Support for step and scheduled autoscaling policies on ECS

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#788]
The Compose CLI currently provides support for [target tracking scaling policies](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-targettracking.html) on ECS. We'd like to gauge interest in [step](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-stepscaling.html) and [scheduled](https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-scheduled-scaling.html) scaling polices before implementing them.

You can read more about autoscaling policies here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html

Please thumbs up this issue if you'd like to see this feature and leave a comment specifying your use case and the policy that you'd like to use.

**Comment by flaviostutz** [comment]
We run a web application that is used by hundreds of teachers preparing activities for their students (they use the website 24x7) and those activities are scheduled to be done, in some cases, by thousands of students in a specific day/hour at once.

We cannot rely on step scaling here, because the students will arrive all at once - at the scheduled time - and if there is insufficient instances to handle the load, our website won't handle the load for several minutes (possibly hours, as we already tested) while the auto-scaling is converging to the optimum state. We really want to "pre-warm" our instances at least 30 minutes before the "punch", by setting the minimum number of instances to a pre-calculated target (according to the number of students we have scheduled) in order to avoid any disruption and after the activities we want to set it to a lower minimum instances.

Clearly in our case we would need some kind of interaction with our database in order to make those schedulings, but a static configuration with pre-defined days/hours would help greatly because some of those activities happens "every monday 8-11am" etc.

**Comment by nebuk89** [comment]
@flaviostutz thanks for the feedback, it is also awesome to hear you are using the Compose-CLI like this with ECS! 
Would you be interested in having a chat about what you are running and in giving some more direct feedback on your experience? If so drop me an email on bengotch@docker.com

Thanks

**Comment by ndeloof** [comment]
This very specific use-case is not what I could name "auto-scaling" but "scheduled-scaling" :P
A possible approach would be for you to update the minimal replica to a know minimal number to support the student-rush load. I don't think AWS has any such component that can cover such a need.

**Comment by ndeloof** [comment]
I'm bit worried that those scheduling strategies (step and scheduled) are highly ECS specific so won't make any sense by compose-spec, an would require a complex nested `x-aws-` extension that we can't validate by compose schema.
